name: Build and Deploy

on:
  release:
    types: [created]

env:
  IMAGE: steamcmd-baseimage

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    #build & push
    - name: Publish Image
      uses: matootie/github-docker@v3.0.0
      id: publish
      with:
        accessToken: ${{ github.token }}
        tag: ${{ github.sha }}
